#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__app_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A MacOS Time Machine Tinkerer.

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    queue       Manage $APP_NAME's queue functionality
    services    Manage $APP_NAME's services
    watch       Watch for changes to files matching configured profiles, and
                optionally take action on identified items

EOF
}

__app_command_queue_command="${1:?"A queue command is required"}"
__app_command_services_command="${2:?"A services command is required"}"
__app_command_watch_command="${3:?"A watch command is required"}"

opt="$4"
args="${@:5}"

case "$opt" in
    exclude)
        echo "path(s) to exclude:" $args
    ;;
    queue)
        source "$__app_command_queue_command" $args
    ;;
    services)
        source "$__app_command_services_command" $args
    ;;
    watch)
        source "$__app_command_watch_command" $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "$APP_VERSION"
    ;;
    -h|--help|*)
        __app_command::usage && exit 0
    ;;
esac
