#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__app_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A MacOS Time Machine Tinkerer.

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    edit        Edit paths for exclusion from, or re-inclusion in Time Machine
                backups
    exemptions  Manage items exempted from $APP_NAME's monitoring
    queue       Manage $APP_NAME's queue functionality
    scan        Scan for existing files matching configured profiles and
                optionally exclude matches from Time Machine backups
    services    Manage $APP_NAME's services
    watch       Watch for changes to files matching configured profiles and
                exclude matches from Time Machine backups

EOF
}

__app_command_edit_command="${1:?"The edit command is required"}"
__app_command_exemptions_command="${2:?"The exemptions command is required"}"
__app_command_queue_command="${3:?"The queue command is required"}"
__app_command_services_command="${4:?"The services command is required"}"
__app_command_watch_command="${5:?"The watch command is required"}"

opt="$6"
args="${@:7}"

case "$opt" in
    edit)
        source "$__app_command_edit_command"
        edit_command::handle $args
    ;;
    exemptions)
        source "$__app_command_exemptions_command"
        exemptions_command::handle $args
    ;;
    queue)
        source "$__app_command_queue_command" $args
    ;;
    scan)
        # TODO: implement the scanner
        echo "scan!"
    ;;
    services)
        source "$__app_command_services_command" $args
    ;;
    watch)
        source "$__app_command_watch_command"
        watch_command::handle $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "$APP_VERSION"
    ;;
    -h|--help|*)
        __app_command::usage && exit 0
    ;;
esac
