#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__app_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A MacOS Time Machine Tinkerer.

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    exclude     Exclude paths from Time Machine backups
    exemptions  Manage paths exempted from $APP_NAME's monitoring
    include     Reinclude paths excluded from Time Machine backups
    queue       Manage $APP_NAME's queue functionality
    scan        Scan for existing files matching configured profiles and
                optionally exclude matches from Time Machine backups
    services    Manage $APP_NAME's services
    watch       Watch for changes to files matching configured profiles and
                optionally exclude matches from Time Machine backups

EOF
}

__app_command_queue_command="${1:?"A queue command is required"}"
__app_command_services_command="${2:?"A services command is required"}"
__app_command_watch_command="${3:?"A watch command is required"}"

opt="$4"
args="${@:5}"

case "$opt" in
    exclude)
        # TODO: implement direct exclusion requests
        echo "path(s) to exclude:" $args
    ;;
    exemptions)
        # TODO: add handling of exemptions (add to list in var/exemptions)
        echo "handle exemptions"
    ;;
    include)
        # TODO: implement direct inclusion requests
        echo "path(s) to include:" $args
    ;;
    queue)
        source "$__app_command_queue_command" $args
    ;;
    scan)
        # TODO: implement the scanner
        echo "scan!"
    ;;
    services)
        source "$__app_command_services_command" $args
    ;;
    watch)
        source "$__app_command_watch_command" && watch_command::handle $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "$APP_VERSION"
    ;;
    -h|--help|*)
        __app_command::usage && exit 0
    ;;
esac
