#!/usr/bin/env bash

__services_command_services_feature="${1:?"A services feature is required"}"
__services_command_args="${@:2}"

source "$__services_command_services_feature"

##
# Cats the command's usage documentation.
##
__services_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION) - Services

Manage $APP_NAME's services.

Usage:  $APP_NAME services [options] <args>

Options:
    -f, --flush Flush the application cache
    -d, --dump  Dump all, or a space-separated list of $APP_NAME's defined
                container services
    -h, --help  Print usage information

EOF
}

##
# Handles incoming services commands.
##
__services_command::handle() {
    local opt=${1}
    local args=${@:2}

    case "$opt" in
        -c|--cache-clear)
            feature::cache_clear
        ;;
        -d|--dump)
            feature::dump $args
        ;;
        # TODO: -r\--resolve
        -h|--help|*)
            __services_command::usage && exit 0
        ;;
    esac
}

__services_command::handle $__services_command_args
