#!/usr/bin/env bash

__services_command_services_feature="${1:?"A services feature is required"}"
__services_command_args="${@:2}"

source "$__services_command_services_feature"

##
# Cats the command's usage documentation.
##
__services_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION) - Services

Manage $APP_NAME's services.

Usage:  $APP_NAME services [options] <args>

Options:
    -f, --flush         Flush the application cache
    -d, --definitions   List named or all application service definitions
    -h, --help          Print usage information

EOF
}

##
# Handles incoming services commands.
##
__services_command::handle() {
    local opt=${1}
    local args=${@:2}

    case "$opt" in
        -f|--flush)
            feature::flush_cache
        ;;
        -d|--definitions)
            feature::list_definitions $args
        ;;
        # TODO: -r\--resolve
        -h|--help|*)
            __services_command::usage && exit 0
        ;;
    esac
}

__services_command::handle $__services_command_args
