#!/usr/bin/env bash

__script_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$__script_dir/../../../bootstrap"

x_attribute_editor="$__project_dir/src/service/exclude/x-attribute-editor"

__X_KEY="com.tomchkk.x_attribute_editor:com_tomchkk_test"
__X_VAL="com.tomchkk.testd"

x_attribute_editor_test::before_each() {
    source "$x_attribute_editor"
}

x_attribute_editor_test::test_write() {
    local actual expected
    local dir=$(time_warp_test::mktmp_dir)
    local not_path="no/path"
    local paths=("$dir" "$not_path")

    # a path must exist
    actual=$(x_attribute_editor::write "$__X_KEY" "$__X_VAL" "$not_path" 2>&1)
    expected="Target path '$not_path' does not exist"
    bash_test::assert_equals "$expected" "$actual"

    x_attribute_editor::write "$__X_KEY" "$__X_VAL" "$dir"
    bash_test::assert_equals "0" "$?"
    bash_test::assert_equals "$__X_KEY: $__X_VAL" "$(xattr -l "$dir")"

    # a path can have spaces
    local spaced="$(time_warp_test::mktmp_dir "foo bar")"
    x_attribute_editor::write "$__X_KEY" "$__X_VAL" "$spaced"
    bash_test::assert_equals "0" "$?"
    bash_test::assert_equals "$__X_KEY: $__X_VAL" "$(xattr -l "$spaced")"
}
