#!/usr/bin/env bash

project_dir=$(dirname $(perl -e "use Cwd 'abs_path'; print abs_path(@ARGV[0])" -- "$0"))
version="$(cat $project_dir/version)"

source "$project_dir/.env"

app_name="${APP_NAME:-$(basename $0)}"
org_id="${ORG_ID:-org}"
org_tmp="/tmp/$org_id.$app_name"

# build an array of config
config=(
    user_config="$HOME/.config/$app_name"
    var="$project_dir/var"
    org_tmp="$org_tmp"
    log_level="${LOG_LEVEL:-DEBUG}"
    excluding_fifo="${EXCLUDING_FIFO:-fifo}"
)

make --file="$project_dir/Makefile" --warn-undefined-variables build ${config[*]}

source "$project_dir/lib/container/index"
source "$project_dir/config/services" "$project_dir" ${config[*]} && __define

unset config

source "$project_dir/src/kernel" $@
