#!/usr/bin/env bash

__project_dir=$(dirname $(perl -e "use Cwd 'abs_path'; print abs_path(@ARGV[0])" -- "$0"))
APP_VERSION="$(cat $__project_dir/version)"

source "$__project_dir/.env"

APP_NAME="${APP_NAME:-$(basename $0)}"
APP_ENV="${APP_ENV:-dev}"
DEBUG="${DEBUG:-true}"
LOG_LEVEL="${LOG_LEVEL:-DEBUG}"

__user_config="$HOME/.config/$APP_NAME"
__profiles_dir="$__user_config/profiles"
__var_dir="$__project_dir/var"
__log_dir="$__var_dir/log"
__org_tmp="/tmp/${ORG_ID:-com.org}.$APP_NAME"

__make_config=(
    user_config="$__user_config"
    var_dir="$__var_dir"
    log_dir="$__log_dir"
    org_tmp="$__org_tmp"
)

# build all the files that will be needed for the project to work
make --file="$__project_dir/Makefile" --warn-undefined-variables build ${__make_config[*]}

source "$__project_dir/src/kernel" $APP_ENV $DEBUG $@

unset \
    __project_dir \
    APP_VERSION \
    APP_NAME \
    APP_ENV \
    DEBUG \
    LOG_LEVEL \
    __user_config \
    __profiles_dir \
    __var_dir \
    __log_dir \
    __org_tmp \
    __make_config

# TODO: go through each point of exit and run `declare -p` to check for memory
# leaks
