#!/usr/bin/env bash

__script_dir="$(dirname "${BASH_SOURCE[0]}")"
source "$__script_dir/../../../bootstrap"

x_attribute_editor="$__project_dir/src/service/editing/x-attribute-editor"
time_machine_editor="$__project_dir/src/service/editing/time-machine-editor"

time_machine_editor_test::before_each() {
    source "$time_machine_editor" "$x_attribute_editor"
}

time_machine_editor_test::test_exclude() {
    # an error code is returned for a non-existent path
    time_machine_editor::exclude "non-existent/path" 2>/dev/null
    bash_test::assert_equals 1 $?

    # an existing path is given excluding x-attributes
    local dir=$(time_warp_test::mktmp_dir)
    time_machine_editor::exclude "$dir"
    bash_test::assert_equals 0 $?
    bash_test::assert_equals \
        "com.apple.metadata:com_apple_backup_excludeItem: com.apple.backupd" \
        "$(xattr -l "$dir")"

    # an existing path with spaces is given excluding x-attributes
    local spaced="$(time_warp_test::mktmp_dir "dir with spaces")"
    time_machine_editor::exclude "$spaced"
    bash_test::assert_equals 0 $?
    bash_test::assert_equals \
        "com.apple.metadata:com_apple_backup_excludeItem: com.apple.backupd" \
        "$(xattr -l "$spaced")"
}

time_machine_editor_test::test_is_excluded() {
    # an error code is returned for a non-existent path
    time_machine_editor::exclude "non-existent/path" 2>/dev/null
    bash_test::assert_equals 1 $?

    local dir=$(time_warp_test::mktmp_dir)

    time_machine_editor::is_excluded "$dir"
    bash_test::assert_equals 1 $?

    time_machine_editor::exclude "$dir"
    bash_test::assert_equals 0 $?

    time_machine_editor::is_excluded "$dir"
    bash_test::assert_equals 0 $?
}

time_machine_editor_test::test_include() {
    # an error code is returned for a non-existent path
    time_machine_editor::include "non-existent/path" 2>/dev/null
    bash_test::assert_equals 1 $?

    # an excluded existing path is re-included
    local dir=$(time_warp_test::mktmp_dir)
    time_machine_editor::exclude "$dir"
    bash_test::assert_equals \
        "com.apple.metadata:com_apple_backup_excludeItem: com.apple.backupd" \
        "$(xattr -l "$dir")"

    time_machine_editor::include "$dir"
    bash_test::assert_equals 0 $?
    bash_test::assert_empty "$(xattr -l "$dir")"

    time_machine_editor::include "$dir" 2>/dev/null
    bash_test::assert_equals 1 $?

    # an excluded existing path with spaces is re-included
    local spaced="$(time_warp_test::mktmp_dir "dir with spaces")"
    time_machine_editor::exclude "$spaced"
    bash_test::assert_equals 0 $?
    bash_test::assert_equals \
        "com.apple.metadata:com_apple_backup_excludeItem: com.apple.backupd" \
        "$(xattr -l "$spaced")"
}
