#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__queue_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION) - Queue

Consume or produce $APP_NAME queue items.

Usage:  $APP_NAME queue [options] <args>

Options:
    -h, --help      Print usage information
    -c, --consume   Open a FIFO pipe to consume items pushed to the queue
    -k, --kill      Kill running queue services
    -r, --report    View a report from running services
    -p, --produce   Produce queue items

EOF
}

__queue_command_consume_feature="${1:?"A consume feature is required"}"
__queue_command_message_feature="${2:?"The message feature is required"}"

opt="$3"
args="${@:4}"

case "$opt" in
    -c|--consume)
        source $__queue_command_consume_feature && feature::consume
    ;;
    -e|--exclude)
        source $__queue_command_message_feature && feature::exclude $args
    ;;
    -k|--kill)
        source $__queue_command_message_feature && feature::kill
    ;;
    -r|--report)
        source $__queue_command_message_feature && feature::report
    ;;
    -p|--produce)
        # source $__queue_command_produce_feature
        # feature::produce $args
        # source $__queue_command_excluding_producer $args
        # - runs `watchexec --resolved-options -- /path/2/producer`
        #   - watches for changes to given paths gets filters from profiles
        #   - ignores changes caused by itself
        #   - passes normalised path to `time-warp match $path` to match the path to a
        #     configured profile
        #   - on successful match, pushes message (timestamp and path) to time-warp/excluding.q file

        # watchexec \
        #     --watch /Users/tom/ \
        #     --filter '**/vendor' \
        #     --ignore '**/vendor/**/vendor/**' \
        #     --no-vcs-ignore \
        #     --no-default-ignore \
        #     --no-shell \
        #     -- "$service/queue/producer"
        #     -- "source $service/queue/producer && producer::handle_event"
    ;;
    -h|--help|*)
        __queue_command::usage && exit 0
    ;;
esac
