#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__queue_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION) - Queue

Manage $APP_NAME's queue functionality.

Usage:  $APP_NAME queue [options] <args>

Options:
    -c, --consume   Open a FIFO pipe to consume pushed items
    -h, --help      Print usage information
    -k, --kill      Kill the running consumer
    -r, --report    View a report from the running consumer
    -p, --produce   Launch $APP_NAME's producing script, used in conjunction
                    with a filesystem watcher, to produce items into $APP_NAME's
                    consumer FIFO pipe

EOF
}

__queue_command_consume_feature="${1:?"The consume feature is required"}"
__queue_command_message_feature="${2:?"The message feature is required"}"
__queue_command_produce_feature="${3:?"The produce feature is required"}"

opt="$4"
args="${@:5}"

case "$opt" in
    -c|--consume)
        source $__queue_command_consume_feature && feature::consume
    ;;
    -k|--kill)
        source $__queue_command_message_feature && feature::kill
    ;;
    -r|--report)
        source $__queue_command_message_feature && feature::report
    ;;
    -p|--produce)
        source $__queue_command_produce_feature && feature::produce $args
    ;;
    -h|--help|*)
        __queue_command::usage && exit 0
    ;;
esac
