#!/usr/bin/env bash

actions="$1"
logger="$2 $3" && shift 3

bash_clash="$@"

source $logger "$(tty)"

if [[ ! -d "$actions" ]]; then
    __log_error "An existing actions directory is required" && exit 1
fi

__handle_message() {
    local message="${1:-[EMPTY]}" && shift
    local args="$@"
    local enquirer="$(source $bash_clash $args && echo $enquirer)"

    action="$actions/$(echo $message | tr '[:upper:]' '[:lower:]')-action"

    if [[ ! -f "$action" ]]; then
        __log_error "An action could not be found for a '$message' message."

        # TODO: can we only use return statements, instead of exits (except
        # where absolutely necessary?)
        return 1 # return to continue execution
    fi

    if [[ ! -w "$enquirer" ]]; then
        __log_error "The enquirer '$enquirer' does not exist."

        return 1 # return to continue execution
    fi

    source $action && __process_action $args
}
