#!/usr/bin/env bash

__script="$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}")"

__test_dir="$(cd "$(dirname "$__script")"; pwd)"
__project_dir="$(dirname "$__test_dir")"

source "$__test_dir/../submodules/autoload"

__bash_clash="$tomchkk_private_projects_bash_clash/src/index"

source "$__project_dir/.env.test"

__org_tmp="$TMPDIR${ORG_ID}.${APP_NAME}.${APP_ENV}"

__make_test=(
    --file="$__project_dir/Makefile"
    --warn-undefined-variables
    "test"
    org_tmp="$__org_tmp"
)
make ${__make_test[@]}

##
# Makes a temp directory within a temp app directory, optionally setting its
# name to the given name, returning the absolute value of the path created.
##
time_warp_test::mktmp_dir() {
    local name="$1"

    local dir=$(mv -v "$(mktemp -d)" "$__org_tmp" | sed -E 's/.* -> (.*)/\1/')

    if [[ -n "$name" ]]; then
        mkdir -p "$dir/$name"
        dir="$dir/$name"
    fi

    echo "$dir"
}
