#!/usr/bin/env bash

__excluding_subscriber_bash_clash="${1:?"bash-clash is required"}"
__excluding_subscriber_service="${2:?"The excluder service is required"}"

source "$__excluding_subscriber_service"

##
# Handles the published topic event.
##
subscriber::on_publish() {
    source $__excluding_subscriber_bash_clash $@

    excluder_service::exclude_path "$(bash_clash::get "path")"

    return $?
}
