#!/usr/bin/env bash

__notifying_subscriber_logger=${1:?"A logger is required"}
__notifying_subscriber_notifications=${@:2}

source $__notifying_subscriber_logger

##
# Handles the published topic event.
##
subscriber::on_publish() {
    log::info "Publishing notifications"

    for notification in ${__notifying_subscriber_notifications[@]}; do
        source "$notification" && notification::notify $@ &
    done

    return $?
}
