#!/usr/bin/env bash

__notifying_subscriber_logger=${1:?"A logger is required"}
__notifying_subscriber_notification=${2:?"A notification is required"}

source $__notifying_subscriber_logger

##
# Handles the published topic event.
##
subscriber::on_publish() {
    log::debug "Notifying user!"

    source $__notifying_subscriber_notification

    notification::notify $@ &

    return 0
}
