#!/usr/bin/env bash

# Implementation of logical testing of watchexec options; can be extended
# accordingly.
#
# Valid filters should include the equal sign - e.g.:
#  --filter="[glob]"
#  -f="[glob]"

##
# Tests whether the given path matches the given filter glob.
##
option_tester::test_filter() {
    local filter=$(echo $1 | sed -E 's/^-(f|-filter)=//')
    local path="$2"

    [[ $path == $filter ]] && return 0 || return 1
}

##
# Tests whether the given path matches the given ignore glob.
##
option_tester::test_ignore() {
    local ignore=$(echo $1 | sed -E 's/^-(i|-ignore)=//')
    local path="$2"

    [[ $path == $ignore ]] && return 0 || return 1
}
