#!/usr/bin/env bash

__time_machine_editor_x_attribute_editor="${1:?"An x-attribute editor is required"}"

source "$__time_machine_editor_x_attribute_editor"

__X_ORG="com.apple.metadata"
__X_NAME="com_apple_backup_excludeItem"

__X_KEY="${__X_ORG}:${__X_NAME}"
__X_VAL="com.apple.backupd"

##
# Excludes the given path from macOS Time Machine backups.
##
time_machine_editor::exclude() {
    local path="$1"

    if $(time_machine_editor::is_excluded "$path"); then
        return 1 # already excluded
    fi

    x_attribute_editor::write "$__X_KEY" "$__X_VAL" "$path"

    return $?
}

##
# Includes the given path in macOS Time Machine backups.
##
time_machine_editor::include() {
    local path="$1"

    if ! $(time_machine_editor::is_excluded "$path"); then
        return 1 # already included
    fi

    x_attribute_editor::delete "$__X_KEY" "$path"

    return $?
}

##
# Reads a given directory for paths currently excluded from Time Machine
# backups.
##
time_machine_editor::read() {
    local path="$1"

    if [[ ! -d "$path" ]]; then
        echo "'$path' is not a directory!"

        return 1
    fi

    mdfind -onlyin "$path" "$__X_NAME = '$__X_VAL'"

    return $?
}

##
# Determines if the given path is currently excluded from Time Machine backups.
##
time_machine_editor::is_excluded() {
    local path="$1"

    if $(x_attribute_editor::contains "$__X_KEY" "$__X_VAL" "$path"); then
        return 0
    fi

    return 1
}
