#!/usr/bin/env bash

source "${1:?"A profile manager is required"}" "${4:?"A profile is required"}"
source "${2:?"A matching strategy is required"}"
source "${3:?"A logger is required"}"

##
# Matches a given path against a set of filter and predicate matching
# strategies for the set profile(s).
##
matcher::match() {
    local path="$@"
    strategy::set_path "$path"

    log::debug "Matching path '$path' against profile(s)"

    for profile in $(profile_manager::get_profiles); do
        log::debug "Matching profile options..."

        local options=$(profile_manager::get_options "$profile")
        if ! $(strategy::path_matches_options "$options"); then
            log::debug "Options do not match!"

            continue # try to match the next profile
        fi

        log::debug "Options matched! Now matching profile predicates..."

        local predicates=$(profile_manager::get_predicates "$profile")
        # the path matches the profile. If it also matches all of the profile's
        # predicates, then we have our match
        if $(strategy::path_matches_predicates "$predicates"); then
            log::debug "Predicates matched!"

            return 0
        fi

        log::debug "Predicates do not match!"
    done

    return 1
}
