#!/usr/bin/env bash

##
# Parses filters from a profile file.
##
profile_parser::parse_filters() {
    echo $(source "$1" && echo ${filters[@]})
}

##
# Parses predicates from a profile file.
##
profile_parser::parse_predicates() {
    echo $(source "$1" && echo ${predicates[@]})
}
