#!/usr/bin/env bash

##
# Parses flags from a profile file.
##
profile_parser::parse_flags() {
    echo $(unset flags && source "$1" && echo ${flags[@]})
}

##
# Parses options from a profile file.
##
profile_parser::parse_options() {
    echo $(unset options && source "$1" && echo ${options[@]})
}

##
# Parses predicates from a profile file.
##
profile_parser::parse_predicates() {
    echo $(unset predicates && source "$1" && echo ${predicates[@]})
}
