#!/usr/bin/env bash

__profile_matcher_profile_manager=${1:?"A profile manager is required"}
__profile_matcher_filter_tester=${2:?"A filter tester is required"}
__profile_matcher_predicate_tester=${3:?"A predicate tester is required"}
__profile_matcher_logger=${4:?"A logger is required"}

__profile_matcher_profiles=${5:?"A profile file or directory is required"}

source "$__profile_matcher_profile_manager" "$__profile_matcher_profiles"
source "$__profile_matcher_filter_tester"
source "$__profile_matcher_predicate_tester"

##
# Matches a given path against a set of predicates.
##
matcher::match() {
    local path="$@"

    source "$__profile_matcher_logger"

    for profile in $(profile_manager::get_profiles); do
        if ! $(__profile_matcher::path_matches_filters "$profile" "$path")
        then
            continue # try to match the next profile
        fi

        # The path matches the profile. If it also matches all of the profile's
        # predicates, then we have our match
        if $(__profile_matcher::path_matches_predicates "$profile" "$path")
        then
            return 0
        fi
    done

    return 1
}

##
# Determines if all filters parsed from the given profile match the given path.
#
__profile_matcher::path_matches_filters () {
    local profile="$1"
    local path="${@:2}"

    local matches=false

    local option
    for option in $(profile_manager::get_options "$profile"); do
        case "$option" in
            -f*|--filter*)
                local filter="$option"

                if ! $(filter_tester::test_filter "$filter" "$path"); then
                    log::debug "Path '$path' does not match filter '$filter'"

                    return 1
                fi

                matches=true

                log::debug "Path '$path' matches filter '$filter'"
            ;;
            *)
                log::debug "Option '$option' is not relevant for path matching"

                continue
            ;;
        esac
    done

    $matches && return 0 || return 1
}

##
# Determines if all predicates parsed from the given profile match the given path.
##
__profile_matcher::path_matches_predicates() {
    local profile="$1"
    local path="${@:2}"

    local matches=false

    local predicate
    for predicate in $(profile_manager::get_predicates "$profile"); do
        case "$predicate" in
            -d*|--directory*)
                if ! $(predicate_tester::test_directory "$predicate" "$path"); then
                    log::debug "Failed directory test: '$predicate'"

                    return 1
                fi

                matches=true

                log::debug "Passed directory test: '$predicate'"
            ;;
            -f*|--file*)
                if ! $(predicate_tester::test_file "$predicate" "$path"); then
                    log::debug "Failed file test: '$predicate'"

                    return 1
                fi

                matches=true

                log::debug "Passed file test: '$predicate'"
            ;;
            *)
                log::debug "Predicate '$predicate' is not supported"

                continue
            ;;
        esac
    done

    $matches && return 0 || return 1
}
