#!/usr/bin/env bash

__excluding_notification_bash_clash=${1:?"bash-clash is required"}
__excluding_notification_title=${2:-"Time Warp"}
__excluding_notification_sound=${3:-"Submarine"}

# TODO: how to set the title in services, considering it would be a string with
# spaces

##
# Sends a notification that path has been excluded from Time Machine backups.
##
notification::notify() {
    source __excluding_notification_bash_clash $@

    # terminal-notifier is a bit verbose and doesn't return bash exit codes,
    # which can prevent parent processes from working properly, so we'll
    # redirect any noise:
    __excluding_notification::do_notify &> /dev/null
}

##
# Perform the actual notification
##
__excluding_notification::do_notify() {
    terminal-notifier \
        -group "$APP_NAME" \
        -title "$__excluding_notification_title" \
        -subtitle "Path excluded from Time Machine backups:" \
        -message $(bash_clash::get "path") \
        -sound "$__excluding_notification_sound" \
        -ignoreDnD
}
