#!/usr/bin/env bash

base="$1" && shift
config="$@"

__define_config() {
    for item in ${config[*]}; do
        [[ "$item" =~ ^(.*)=(.*)$ ]]
        key="$(echo ${BASH_REMATCH[1]} | sed "s/_/-/g")"
        value="${BASH_REMATCH[2]}"

        __container_add "$key" "$value"
    done
}

__define_parameters() {
    __container_add "excluding-pipe" \
        "$(__container_get "org-tmp")/$(__container_get "excluding-fifo")"

    __container_add "config-dir" "$base/config"
    __container_add "lib-dir" "$base/lib"
    __container_add "src-dir" "$base/src"

    # add all src dirs as container parameters
    for dir in $(find $base/src -mindepth 1 -maxdepth 1 -type d); do
        __container_add "$(basename $dir)-dir" "$dir"
    done

    __container_add "message-routing" \
        "$(__container_get "message-dir")/kill-message::$(__container_get "excluding-pipe")" \
        "$(__container_get "message-dir")/report-message::$(__container_get "excluding-pipe")"
}

__define_services() {
    # lib
    __container_add "logger" \
        "$(__container_get "lib-dir")/log-slog/index" \
        "$(__container_get "log-level")"
    __container_add "bash-clash" "$(__container_get "lib-dir")/bash-clash/index"

    # commands
    __container_add "time-warp-command" \
        "$(__container_get "command-dir")/time-warp/index"
    __container_add "queue-command" "$(__container_get "command-dir")/queue/index"
    __container_add "watch-command" "$(__container_get "command-dir")/watch/index"

    # handlers
    __container_add "message-handler" \
        "$(__container_get "handler-dir")/message-handler" \
        "$(__container_get "action-dir")" \
        "$(__container_get "logger")" \
        "$(__container_get "bash-clash")"

    # consumers
    __container_add "excluding-consumer" \
        "$(__container_get "service-dir")/queue/consumer" \
        "$(__container_get "excluding-pipe")" \
        "$(__container_get "message-handler")" \
        "$(__container_get "logger")"

    # buses
    __container_add "message-bus" \
        "$(__container_get "bus-dir")/message-bus" \
        "$(__container_get "message-dir")" \
        "$(__container_get "logger")" \
        "$(__container_get "message-routing")"
}

__define() {
    __define_config
    __define_parameters
    __define_services

    unset base
    unset config
}
