#!/usr/bin/env bash

__services_config="$@"

##
# Defines available config.
##
__services::define_config() {
    local key
    local value

    for item in ${__services_config[@]}; do
        [[ "$item" =~ ^(.*)=(.*)$ ]]
        key="${BASH_REMATCH[1]}"
        value="${BASH_REMATCH[2]}"

        container::add_scalar "$key" "$value"
    done
}

##
# Defines available parameters.
##
__services::define_parameters() {
    # dirs
    container::add_scalar "view-dir" "@{project-dir}/src/view"

    # pipes
    container::add_scalar "excluding-pipe" "@{org-tmp}/excluding-pipe"

    # message routing
    container::add_array "message-routing" \
        -- "\@kill-message::@excluding-pipe" \
        -- "\@publish-message::@excluding-pipe" \
        -- "\@report-message::@excluding-pipe"

    # publishable topics
    container::add_scalar "time-machine-exclude-topic" "time-machine-exclude"

    # watchexec producer events
    container::add_array "excluding-producer-events" -- "created" -- "renamed"

    # publish action subscribers
    container::add_array "publish-action-subscribers" \
        -- "\@excluding-action-subscriber::@time-machine-exclude-topic" \
        -- "\@excluding-notification-subscriber::@time-machine-exclude-topic"

    container::add_array "excluding-notifications" \
        -- "@terminal-notification" \
        -- "@slack-notification"
}

##
# Defines available services.
##
__services::define_services() {
    # submodule services
    container::add_service "bash-clash" \
        "$tomchkk_private_projects_bash_clash/src/index"

    container::add_service "file-logger" \
        "$tomchkk_private_projects_bash_logger/src/index" \
            -- "@log-level" \
            -- "@file-channel"

    container::add_service "stdout-logger" \
        "$tomchkk_private_projects_bash_logger/src/index" \
            -- "@log-level" \
            -- "@stdout-channel" \
            -- " =>" # TODO: figure-out why '->' is not valid

    # commands
    container::add_service "app-command" \
        "@{project-dir}/src/command/app-command" \
            -- "@queue-command" \
            -- "@services-command" \
            -- "@watch-command"

    container::add_service "queue-command" \
        "@{project-dir}/src/command/queue-command" \
            -- "@consume-feature" \
            -- "@message-feature" \
            -- "@produce-feature"

    container::add_service "services-command" \
        "@{project-dir}/src/command/services-command" \
            -- "@services-feature"

    container::add_service "watch-command" \
        "@{project-dir}/src/command/watch-command" \
            -- "@watch-feature" \
            -- "@profiles-dir" \
            -- "$HOME"

    # features
    container::add_service "consume-feature" \
        "@{project-dir}/src/feature/consume-feature" \
            -- "@excluding-consumer"

    container::add_service "message-feature" \
        "@{project-dir}/src/feature/message-feature" \
            -- "@message-bus"

    container::add_service "produce-feature" \
        "@{project-dir}/src/feature/produce-feature" \
            -- "@excluding-producer" \
            -- "@stdout-logger"

    container::add_service "services-feature" \
        "@{project-dir}/src/feature/services-feature"

    container::add_service "watch-feature" \
        "@{project-dir}/src/feature/watch-feature" \
            -- "@watchexec-options-resolver" \
            -- "@excluding-consumer" \
            -- "@message-bus" \
            -- "@stdout-logger" \
            -- "@debug"

    # consumers
    container::add_service "excluding-consumer" \
        "@{project-dir}/src/service/queue/consumer" \
           --  "@excluding-pipe" \
           --  "@stdout-logger" \
           --  "@message-handler"

    # file profilers
    container::add_service "profile-parser" \
        "@{project-dir}/src/service/profile/profile-parser"

    container::add_service "profile-manager" \
        "@{project-dir}/src/service/profile/profile-manager" \
            -- "@profile-parser" \
            -- "@stdout-logger"

    container::add_service "watchexec-tester" \
        "@{project-dir}/src/service/profile/tester/watchexec-tester"

    container::add_service "predicate-tester" \
        "@{project-dir}/src/service/profile/tester/predicate-tester"

    container::add_service "profile-matcher" \
        "@{project-dir}/src/service/profile/profile-matcher" \
            -- "@profile-manager" \
            -- "@watchexec-tester" \
            -- "@predicate-tester" \
            -- "@stdout-logger"

    container::add_service "watchexec-options-resolver" \
        "@{project-dir}/src/service/profile/resolver/watchexec-options-resolver" \
            -- "@profile-manager" \
            -- "@watchexec-filter-validator" \
            -- "@stdout-logger"

    container::add_service "watchexec-filter-validator" \
        "@{project-dir}/src/service/profile/resolver/watchexec-filter-validator"

    # producers
    container::add_service "excluding-producer" \
        "@{project-dir}/src/service/queue/producer" \
            -- "@stdout-logger" \
            -- "@message-bus" \
            -- "@time-machine-exclude-topic" \
            -- "@profile-matcher" \
            -- "@excluding-producer-events"

    # buses
    container::add_service "message-bus" \
        "@{project-dir}/src/bus/message-bus" \
            -- "@stdout-logger" \
            -- "@message-routing"

    # messages
    container::add_service "kill-message" \
        "@{project-dir}/src/message/kill-message"

    container::add_service "publish-message" \
        "@{project-dir}/src/message/publish-message"

    container::add_service "report-message" \
        "@{project-dir}/src/message/report-message"


    # handlers
    container::add_service "message-handler" \
        "@{project-dir}/src/handler/message-handler" \
            -- "@stdout-logger"

    # message actions
    container::add_service "kill-action" \
        "@{project-dir}/src/action/kill-action" \
            -- "@bash-clash" \
            -- "@stdout-logger"

    container::add_service "publish-action" \
        "@{project-dir}/src/action/publish-action" \
            -- "@stdout-logger" \
            -- "@bash-clash" \
            -- "@publish-action-subscribers"

    container::add_service "report-action" \
        "@{project-dir}/src/action/report-action" \
            -- "@bash-clash" \
            -- "@view-dir"

    # subscribers
    container::add_service "excluding-action-subscriber" \
        "@{project-dir}/src/subscriber/excluding-subscriber" \
            -- "@bash-clash" \
            -- "@excluder-service"

    container::add_service "excluding-notification-subscriber" \
        "@{project-dir}/src/subscriber/notifying-subscriber" \
            -- "@stdout-logger" \
            -- "@excluding-notifications"

    # subscriber actions
    container::add_service "excluder-service" \
        "@{project-dir}/src/service/excluder/excluder-service" \
            -- "@stdout-logger"

    # notifications
    container::add_service "terminal-notification" \
        "@{project-dir}/src/notification/excluding/terminal-notification" \
            -- "@bash-clash" \
            -- "Time Warp" \
            -- "Path excluded from Time Machine backups:"

    container::add_service "slack-notification" \
        "@{project-dir}/src/notification/excluding/slack-notification"
}

__services::define_config
__services::define_parameters
__services::define_services

unset __services_config
