#!/usr/bin/env bash

source "$(dirname "${BASH_SOURCE[0]}")/../../bootstrap"

message_cache="$__project_dir/src/service/exclude/message-cache"
message_cache_dir=""
seconds_to_live=10

message_cache_test::before_each() {
    message_cache_dir=$(time_warp_test::mktmp_dir)

    source "$message_cache" "$message_cache_dir" "$seconds_to_live"
}

message_cache_test::test_contains() {
    local actual expected

    # an empty cache can't contain anything
    actual="$(message_cache::contains "item-1"; echo $?)"
    bash_assert::assert_equals 1 "$actual"

    # the cache does contain an existing item
    touch "$message_cache_dir/item-1"
    actual="$(message_cache::contains "item-1"; echo $?)"
    bash_assert::assert_equals 0 "$actual"

    # the cache does not contain an non-existing item when not empty
    actual="$(message_cache::contains "item-2"; echo $?)"
    bash_assert::assert_equals 1 "$actual"

    # invalid items are removed from the cache as a consequence of calling this
    # method
    touch -t $(date -v-1d +%Y%m%d%H%M) "$message_cache_dir/item-2"
    actual="$(message_cache::contains "item-1"; echo $?)"
    bash_assert::assert_equals 0 "$actual"
    actual="$(message_cache::contains "item-2"; echo $?)"
    bash_assert::assert_equals 1 "$actual"
}

message_cache_test::test_add() {
    local actual expected

    # an item is added to the cache
    actual=$(message_cache::add "item-1"; echo $?)
    bash_assert::assert_equals 0 "$actual"
    actual=$([[ -f "$message_cache_dir/item-1" ]] && echo 0)
    bash_assert::assert_equals 0 "$actual"

    # an existing item is not re-added to the cache
    actual=$(message_cache::add "item-1"; echo $?)
    bash_assert::assert_equals 1 "$actual"
}

message_cache_test::test_remove() {
    local actual expected

    # an non-existing item is not removed from the cache
    actual=$(message_cache::remove "item-1"; echo $?)
    bash_assert::assert_equals 1 "$actual"

    # an existing item is removed from the cache
    touch "$message_cache_dir/item-1"
    actual=$(message_cache::remove "item-1"; echo $?)
    bash_assert::assert_equals 0 "$actual"
}
