#!/usr/bin/env bash

__parse_arguments() {
    local parameters=()
    local switch
    local value

    while [[ $# > 0 ]]; do
        if [[ "$1" =~ ^--(.*)=(.*)$ ]]; then
            switch="${BASH_REMATCH[1]}" && value="${BASH_REMATCH[2]}" && shift
        else
            switch=$1 && value=$2 && shift 2
        fi

        parameters+=("$(echo $switch | sed 's/^--//' | sed 's/-/_/g')=$value")
    done

    echo "${parameters[*]}"
}

__parameters=("$(__parse_arguments $@)")

declare ${__parameters[*]} && unset __parameters
