#!/usr/bin/env bash

# TODO: create and pass in an excluder service and call it (avoid, if possible,
# the use of an internal call to time-machine)

__exclude_action_logger=${1:?"A logger is required"}
__exclude_action_bash_clash=${2:?"bash-clash is required"}

source $__exclude_action_logger

##
# Excludes a path from Time Machine backups
##
action::process_action() {
    source $__exclude_action_bash_clash $@

    local path=$(bash_clash::get "path")

    log::info "Excluding path '$path' from Time Machine backups"
}
