#!/usr/bin/env bash

bash_clash=$(__container_get "bash-clash")

__process_action() {
    source "$bash_clash" "$@"

    echo -e "\nKilling the queue at '$pipe' (pid: $queue_pid)" > $enquirer

    # exit the current process (the consumer)
    exit 0
}
