#!/usr/bin/env bash

__kill_action_bash_clash="$1"
__kill_action_logger="$2" && $LOAD $__kill_action_logger

##
# Exits the current process.
##
action::process_action() {
    $LOAD "$__kill_action_bash_clash" $@

    local pipe=$(bash_clash::get "pipe")
    local queue_pid=$(bash_clash::get "queue_pid")
    local enquirer=$(bash_clash::get "enquirer")

    log_slog::info "Killing the queue at '$pipe' (pid: $queue_pid)"

    # exit the current process (the consumer)
    exit 0
}
