#!/usr/bin/env bash

bash_clash=$(__container_get "bash-clash")
view_dir=$(__container_get "view-dir")

__process_action() {
    source "$bash_clash" "$@"

    local uptime=$(date -r $(($uptime - 3600)) +"%-Hh %-Mm %-Ss")

    echo -e "$(source $view_dir/report-view)" > $enquirer
}
