#!/usr/bin/env bash

source "${1:?"A message bus is required"}"

##
# Dispatches a kill message via the message bus
##
feature::kill() {
    message_bus::dispatch_message "KILL"
}

##
# Dispatches a report message via the message bus
##
feature::report() {
    message_bus::dispatch_message "REPORT"
}
