#!/usr/bin/env bash

__message_feature_bus=${1:?"A message bus is required"}
__message_feature_logger=${2:?"A logger is required"}

source $__message_feature_bus
source $__message_feature_logger

##
# Dispatches a kill message via the message bus
##
feature::kill() {
    message_bus::dispatch_message "KILL"
}

##
# Dispatches a report message via the message bus
##
feature::report() {
    message_bus::dispatch_message "REPORT"
}
