#!/usr/bin/env bash

__services_feature_logger="${1:?"A logger is required"}"
__services_feature_cache_dir="${2:?"The cache dir is required"}"

source "$__services_feature_logger"

##
# Flush the app's service cache dir.
##
feature::flush_cache() {
    if [[ ! -d "$__services_feature_cache_dir" ]]; then
        log::error "'$__services_feature_cache_dir' is not a valid directory"

        return 1
    fi

    rm "${__services_feature_cache_dir}"/*

    return $?
}

##
# List named or all application service definitions
##
feature::list_definitions() {
    container::dump $@
}
