#!/usr/bin/env bash

__time_warp_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A MacOS Time Machine Tinkerer.

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    queue       Consume or produce queue items.
    watch       Recursively watch a path, or paths, for changes to files matching
                configured file profile filters.

EOF
}

opt="$1" && shift
args="$@"

case "$opt" in
    exclude)
        # excludes item from backups
        # TODO:
        #  - on success, pushes item to time-warp/excluded.q
        #  - on fail, pushes item to time-warp/errored.q

        echo "path(s) to exclude:" $args
    ;;
    queue)
        source $(container::resolve "queue-command") $args
    ;;
    watch)
        source $(container::resolve "watch-command") $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "__version"
    ;;
    -h|--help|*)
        __time_warp_command::usage && exit 0
    ;;
esac
