#!/usr/bin/env bash

##
# Cats the command's usage documentation.
##
__time_warp_command::usage() {
    cat << EOF

$APP_NAME ($APP_VERSION)

A MacOS Time Machine Tinkerer.

Usage:  $APP_NAME [option]
        $APP_NAME <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    queue       Consume or produce queue items.
    watch       Recursively watch a path, or paths, for changes to files matching
                configured file profile filters.

EOF
}

__time_warp_command_queue_command="$1"
__time_warp_command_watch_command="$2"

opt="$3" && shift 3

case "$opt" in
    exclude)
        # excludes item from backups
        # TODO:
        #  - on success, pushes item to time-warp/excluded.q
        #  - on fail, pushes item to time-warp/errored.q

        echo "path(s) to exclude:" $@
    ;;
    queue)
        $LOAD $__time_warp_command_queue_command $@
    ;;
    watch)
        $LOAD $__time_warp_command_watch_command $@
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "$APP_VERSION"
    ;;
    -h|--help|*)
        __time_warp_command::usage && exit 0
    ;;
esac
