#!/usr/bin/env bash

__command_usage() {
    cat << EOF
$app_name ($version)

A MacOS Time Machine Tinkerer.

Usage:  $app_name [option]
        $app_name <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    queue       Consume or produce queue items.
    watch       Recursively watch a path, or paths, for changes to files matching
                configured file profile filters.

EOF
}

opt="$1" && shift
args="$@"

case "$opt" in
    exclude)
        # excludes item from backups
        # TODO:
        #  - on success, pushes item to time-warp/excluded.q
        #  - on fail, pushes item to time-warp/errored.q

        echo "path(s) to exclude:" $args
    ;;
    queue)
        source $(__container_get "queue-command") $args
    ;;
    watch)
        source $(__container_get "watch-command") $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help queue watch"
    ;;
    -v|--version)
        echo "$version"
    ;;
    -h|--help|*)
        __command_usage && exit 0
    ;;
esac
