#!/usr/bin/env bash

##
# Ships a debug log for the dependency loader, maintaining the logger in a sub
# process to avoid clashing with other loaded loggers.
##
__dependency_loader::debug() {
    local message="${1:?"A log message is required"}"
    local context="${@:2}"

    (
        builtin source $(container::resolve "@file-logger")
        log_slog::debug "$message" ${context[*]}
    )
}

##
# Overrides the builtin source function to enable dependency loading.
##
source () {
    __service_source="${1:?"A service, alias or filename argument is required"}"
    __service_args=${@:2}

    if [[ -f "$__service_source" ]]; then
        # we're dealing with a plain ole' file to be sourced, maybe with some args..
        builtin source "$__service_source" $__service_args
        exit 0
    fi

    __service_alias="$__service_source"
    __service_definition=($(container::get_definition "$__service_alias"))

    if [[ $? -eq 1 ]]; then
        echo "The service '$__service_alias' could not be loaded."
        exit 1
    fi

    __service_source=${__service_definition[0]}
    __service_dependencies=()

    __dependency_loader::debug "Loading '$__service_alias'" "$__service_source"

    for __service_dependency in ${__service_definition[*]:1}; do
        __dependency_definition=(
            $(container::get_definition "$__service_dependency" "$__service_dependency")
        )

        if [[ -f ${__dependency_definition[0]} ]]; then
            __service_dependencies+=($__service_dependency)
            __dependency_loader::debug "Loadable dependency '$__service_dependency'" "${__dependency_definition[0]}"
        else
            __service_dependencies+=(${__dependency_definition[*]})
            __dependency_loader::debug "Non-loadable dependency '$__service_dependency'" "${__dependency_definition[*]}"
        fi
    done

    builtin source $__service_source ${__service_dependencies[*]} $__service_args

    unset \
        __service_alias \
        __service_args \
        __service_definition \
        __service_source \
        __service_dependencies \
        __service_dependency \
        __dependency_definition
}
