#!/usr/bin/env bash

command="$src/command"
service="$src/service"

_usage() {
    cat << EOF
$app_name ($version)

A MacOS Time Machine Tinkerer.

Usage:  $app_name [option]
        $app_name <command> [args]

Options:
    -h, --help      Print usage information
    -l, --list      Print a list of available commands and options
    -v, --version   Print the version number

Commands:
    queue       Consume or produce queue items.
    watch       Recursively watch a path, or paths, for changes to files matching
                configured file profile filters.

EOF

    exit 0
}

opt="$1" && shift
args="$@"

case "$opt" in
    queue)
        . "$command/queue/index" $args
    ;;
    watch)
        . "$command/watch/index" $args
    ;;
    -l|--list)
        echo "-l --list -v --version -h --help" && \
        echo "watch"
    ;;
    -v|--version)
        echo "$version"
    ;;
    -h|--help|*)
        _usage
    ;;
esac
