#!/usr/bin/env bash

# build an array of config
__kernel_config=(
    app_env="$1"
    debug="$2"
    var_dir="$__var_dir"
    log_dir="$__log_dir"
    org_tmp="$__org_tmp"
    log_level="${LOG_LEVEL:-"DEBUG"}"
)
__kernel_args=${@:3}

# import container functionality
source "$__project_dir/lib/container/index"

# boot app config, parameters and services
source "$__project_dir/config/services" "$__project_dir" ${__kernel_config[*]}
services::define

# replace the 'source' builtin with dependency-loader functionality
source $__project_dir/lib/container/dependency-loader

# handle the request
source @time-warp-command $__kernel_args

unset \
    __kernel_config \
    __kernel_args
