#!/usr/bin/env bash

__excluding_notification_bash_clash="${1:?"bash-clash is required"}"
__excluding_notification_title="${2}"
__excluding_notification_subtitle="$3"
__excluding_notification_sound="$4"
__excluding_notification_ignore_dnd="$5"

##
# Sends a notification that path has been excluded from Time Machine backups.
##
notification::notify() {
    source "$__excluding_notification_bash_clash" "$@"

    local path="$(bash_clash::get "path")"

    local args=(
        -title "${__excluding_notification_title:-"Title"}"
        -subtitle "${__excluding_notification_subtitle:-"Subtitle"}"
        -message "$path"
        -sound "${__excluding_notification_sound:-"Submarine"}"
        -execute "$(which $APP_NAME) exemptions --add $path"
        "$($__excluding_notification_ignore_dnd && echo "-ignoreDnD")"
    )

    # terminal-notifier is a bit verbose and doesn't return bash exit codes,
    # which can prevent parent processes from working properly, so we'll just
    # redirect any 'noise' that it creates:
    terminal-notifier "${args[@]}" &> /dev/null
}
