#!/usr/bin/env bash

__message_bus_logger="${1:?"Logger is a required parameter"}" \
    && source $__message_bus_logger
__message_bus_routing=${@:2}

if [[ -z "$__message_bus_routing" ]]; then
    log::error "No message routing is defined" && exit 1
fi

##
# Dispatches a message for an action via a given channel.
##
message_bus::dispatch_message() {
    local action="${1:?"An action type is required"}"
    local args=${@:2}

    local message="@$(echo $action | tr '[:upper:]' '[:lower:]')-message"
    local channel

    for route in ${__message_bus_routing[*]}; do
        # expected routing format:
        # - @action-message-alias::/channel/to/write/2
        if [[ "$route" =~ ^"$message"::(.+)$ ]]; then
            channel=${BASH_REMATCH[1]}
            break
        fi
    done

    if [[ -z "$channel" ]]; then
        log::error "A message route is not defined for the '$action' message."
        exit 1
    fi

    if [[ ! -e "$channel" ]] || [[ ! -w "$channel" ]]; then
        log::error "The channel '$channel' does not exist or is not writable."
        exit 1
    fi

    source $message && message::send_message $args > $channel

    log::info "'$action' message was dispatched." $args
}
