#!/usr/bin/env bash

messages="$1" && shift
routing="$@"

if [[ ! -d "$messages" ]]; then
    echo "Error: An existing messages directory is required" && exit 1
fi

if [[ -z "$routing" ]]; then
    echo "Error: No message routing is defined" && exit 1
fi

__dispatch_message() {
    local action="${1:-[empty]}"

    local message="$messages/$(echo $action | tr '[:upper:]' '[:lower:]')-message"

    if [[ ! -f "$message" ]]; then
        echo "Error: A message could not be found for the '$action' action." && exit 1
    fi

    local target
    for route in ${routing[*]}; do
        if [[ "$route" == "$message::"* ]]; then
            target=$(echo "$route" | sed -E "s/.*::(.*)/\1/") && break;
        fi
    done

    if [[ -z "$target" ]]; then
        echo "$target"
        echo "Error: A message route is not defined for the '$action' message." && exit 1
    fi

    if [[ ! -e "$target" ]]; then
        echo "Error: The target '$target' does not exist." && exit 1
    fi

    source $message && __send_message > $target

    echo "'$action' Message dispatched"
}
